In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

# I/ NumPy:

**NumPy (Numerical Python)** is the fundamental package required for **high performance scientific computing** and data analysis. Below are somethings it provides:
- ndarray = a fast and space-efficient multidimensional array providing vectorized arithmetic operations and sophisticated broadcasting capabilities
- Standard mathematical functions for fast operations on entire arrays of data without having to write loops
- Tools for reading / writing array data to disk and working with memory-mapped files
- Linear algebra, random number generation, and Fourier transform capabilities
- Tools for integrating code written in C, C++, and Fortran

## 1) ndarray:

### Creating ndarray

In [14]:
data = np.array([1,2,3])
data

array([1, 2, 3])

ndarray is a generic multidimensional container for homogeneous data: **all of the elements must be the same type**. 

Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data type of the array:

In [17]:
data = np.array([1,2.2,3.4])
data

array([1. , 2.2, 3.4])

In [18]:
print('dtype = ', data.dtype)
print('shape = ', data.shape)

dtype =  float64
shape =  (3,)


### Initialize an array:

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

***Note***: *It’s not safe to assume that np.empty will return an array of all zeros. In many cases, like below, it will return uninitialized garbage values.*

In [27]:
np.empty(5)

array([1.28098993e-311, 2.03060980e-321, 5.15804534e-321, 1.69121095e-306,
       9.34602321e-307])

**arange** is an array-valued version of the built-in Python range function:

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Typecasting:

Convert or cast an array from one dtype to another using ndarray’s **astype** method:

In [33]:
data = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
data

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [36]:
data = data.astype(np.int32)
data

array([ 3, -1, -2,  0, 12, 10])

### Operations between Arrays and Scalars

**Vectorization**: Arrays are important because they enable you to **express batch operations on data without writing any for loops** (element-wise operations).

In [40]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [41]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

### Indexing and Slicing